CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,
admin INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS movies(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
description TEXT,
image_path TEXT NOT NULL,
release_year INTEGER NOT NULL,
director TEXT NOT NULL,
rating INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
movie_id INTEGER NOT NULL,
rating INTEGER NOT NULL,
description TEXT,
FOREIGN KEY (user_id) REFERENCES users (id),
FOREIGN KEY (movie_id) REFERENCES movies (id)
);

